services:
  redis-master:
    command:
    - redis-server
    - --port
    - '6379'
    container_name: redis-master
    hostname: redis-master
    image: redis
    ports:
    - 6379:6379

  demo:
    container_name: demo
    depends_on:
      - redis-master
    hostname: demo
    environment:
        - REDIS_SERVER=redis-master
    image: anishnath/demo:v1
    ports:
    - 8080

  demo1:
    container_name: demo1
    depends_on:
      - redis-master
    hostname: demo1
    environment:
        - REDIS_SERVER=redis-master
    image: anishnath/demo:v2
    ports:
    - 8080
  
  web:
    container_name: web
    depends_on:
      - demo
      - demo1
      - redis-master
    hostname: web
    image: anishnath/demo:nginx-elb
    ports:
    - 80:80  
    
version: '3'