services:
  redis-master:
    command:
    - redis-server
    - --port
    - '6379'
    container_name: redis-master
    hostname: redis-master
    image: redis
    ports:
    - 6379

  demo:
    container_name: demo
    depends_on:
      - redis-master
    hostname: demo
    deploy: 
        mode: replicated
        replicas: 2
    environment:
        - REDIS_SERVER=redis-master
    image: anishnath/demo:v2
    ports:
    - 8080:8080  
version: '3'