services:
  redis-master:
    command:
    - redis-server
    - --port
    - '6379'
    container_name: redis-master
    hostname: redis-master
    image: redis
    ports:
    - 6379

  demo:
    container_name: demo
    depends_on:
      - api
    hostname: demo
    deploy: 
        mode: replicated
        replicas: 1
    environment:
      - REDIS_API_PORT=8080
      - REDIS_API_SERVER=api
    image: anishnath/demo:v4
    ports:
    - 8080

  demo1:
    container_name: demo1
    depends_on:
      - api
    hostname: demo1
    deploy: 
        mode: replicated
        replicas: 1
    hostname: demo1
    environment:
      - REDIS_API_PORT=8080
      - REDIS_API_SERVER=api
    image: anishnath/demo:v5
    ports:
    - 8080  
  
  api:
    container_name: api
    depends_on:
      - redis-master
    hostname: api
    environment:
        - REDIS_SERVER=redis-master
        - REDIS_PORT=6379
    image: anishnath/demo:api
    ports:
    - 8080

  web:
    container_name: web
    depends_on:
      - demo
      - demo1
      - redis-master
      - api
      - logstash
    hostname: web
    image: anishnath/demo:nginxv1
    ports:
    - 80:80

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    container_name: logstash
    depends_on:
      - elasticsearch
    hostname: logstash
    image: anishnath/demo:logstash
    ports:
    - 5140

  kibana:
    container_name: kibana
    hostname: kibana
    links:
      - elasticsearch
      - logstash
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601

version: '3'